In [4]:
print("Hello World")

Hello World


In [5]:
import torch
print(torch.__version__)

2.11.0+cpu


In [6]:
z = torch.zeros(5,3)
z
print(z.dtype)

torch.float32


In [7]:
i = torch.ones((5,3), dtype=torch.int16)
i

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [8]:
torch.manual_seed(1729)
r1 = torch.rand(3,3)
print('A random tensor')
print(r1)

r2 = torch.rand(3,3)
print('Different tensor')
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(3,3)
print('IS it the same as 1?')
print(r3)

A random tensor
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691],
        [0.2332, 0.4047, 0.2162]])
Different tensor
tensor([[0.9927, 0.4128, 0.5938],
        [0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])
IS it the same as 1?
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691],
        [0.2332, 0.4047, 0.2162]])


In [9]:
import torch.nn as nn
import torch.nn.functional as F

In [10]:
import torch.nn as nn
import torch.nn.functional as F

class LeNet(nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 3x3 square convolution kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


Working with Newral Networks

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import dataloader
import torchvision.datasets as datasets
import  torchvision.transforms as transforms

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

class NN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)

    def forward(self, x):
        x = x.reshape(x.shape[0], -1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyperparameters
input_size = 784
num_classes = 10
learning_rate = 0.001
batch_size = 64
num_epochs = 1

# Data
train_dataset = datasets.MNIST(root='dataset/', train=True, transform=transforms.ToTensor(), download=True)
test_dataset = datasets.MNIST(root='dataset/', train=False, transform=transforms.ToTensor(), download=True)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

# Model
model = NN(input_size=input_size, num_classes=num_classes).to(device)

# Loss + Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(train_loader):

        #Get data to Cuda if possible
        data = data.to(device)
        targets = targets.to(device)

        #Get correct shape:
        data = data.reshape(data.shape[0], -1)

        #Forward
        scores = model(data)
        loss = criterion(scores, targets)

        #Backward
        loss.backward()

        #Grading dataset
        optimizer.step()


#Check Accuracy on training and test data
def check_accuracy(loader, model):
    if loader.datasets.train:
        print("Checking accuracy on training data")
    else:
        print("Checking accuracy on testing data")

    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device)
            y = y.to(device=device)
            x = x.reshape(x.shape[0], -1)

            scores = model(x)
            _, predictions = scores.max(1)
            num_correct += (predictions==y).sum()
            num_samples += predictions.size(0)
        print(f"Got {num_correct/(num_samples)} with accuracy {float(num_correct)/float(num_samples)*100:.2f}%")



In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

class NN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)

    def forward(self, x):
        x = x.reshape(x.shape[0], -1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyperparameters
input_size = 784
num_classes = 10
learning_rate = 0.001
batch_size = 64
num_epochs = 1

# Data
train_dataset = datasets.MNIST(root='dataset/', train=True, transform=transforms.ToTensor(), download=True)
test_dataset = datasets.MNIST(root='dataset/', train=False, transform=transforms.ToTensor(), download=True)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

# Model
model = NN(input_size=input_size, num_classes=num_classes).to(device)

# Loss + Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(train_loader):

        #Get data to Cuda if possible
        data = data.to(device)
        targets = targets.to(device)

        #Get correct shape:
        data = data.reshape(data.shape[0], -1)

        #Forward
        scores = model(data)
        loss = criterion(scores, targets)

        #Backward
        loss.backward()

        #Grading dataset
        optimizer.step()


#Check Accuracy on training and test data
def check_accuracy(loader, model):
    if loader.datasets.train:
        print("Checking accuracy on training data")
    else:
        print("Checking accuracy on testing data")

    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device)
            y = y.to(device=device)
            x = x.reshape(x.shape[0], -1)

            scores = model(x)
            _, predictions = scores.max(1)
            num_correct += (predictions==y).sum()
            num_samples += predictions.size(0)
        print(f"Got {num_correct/(num_samples)} with accuracy {float(num_correct)/float(num_samples)*100:.2f}%")



Dense Layer From Scratch


In [14]:
import torch
import torch.nn as nn

class MyDenselayer(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(MyDenselayer, self).__init__()

        #Initialize Weight and Balance
        self.W = nn.Parameter(torch.randn(input_dim, output_dim))
        self.b = nn.Parameter(torch.zeros(output_dim))

    def forward(self, inputs):
        #Forward Propagates the inputs
        
        z = torch.matmul(inputs, self.W) + self.b

        output = torch.sigmoid(z)
        return output


You could just call the Linearization


In [15]:
import torch.nn as nn
layer = nn.Linear(in_features=2, out_features=2)

<b style="color:cyan; font-size:20px;">
29TH APRIL, 2026 Practice
</b>


In [18]:
nn.Sequential(
    nn.Linear(784, 128),
    nn.Sigmoid()
)

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): Sigmoid()
)

<b style= "color:cyan; font-size:20px">
Loss Computation
</b>

Example 1 — Regression (MSE)

In [22]:
import torch
import torch.nn as nn

criterion = nn.MSELoss()

pred = torch.tensor([2.5, 0.0, 2.1])
target = torch.tensor([3.0, -0.5, 2.0])

loss = criterion(pred, target)
print(loss)

tensor(0.1700)


Example 2 — Binary Classification

In [26]:
criterion = nn.BCELoss()

pred = torch.tensor([0.8, 0.3, 0.6]) #Probabilities
target = torch.tensor([1.0, 0.0, 1.0])

loss = criterion(pred, target)
print(loss)

tensor(0.3635)


Example 3 — Multi-Class (MOST COMMON)

In [27]:
criterion = nn.CrossEntropyLoss()

outputs = torch.tensor([[2.0, 1.0, 0.1]])
target = torch.tensor([0])

print(f"Loss:{criterion(outputs, target)}")

Loss:0.4170299470424652


<b style= "color:cyan; font-size:20px">
Recurrent Nural Networks, Transformers and Attention
</b>

In [31]:
from torch.nn import RNN
model = RNN(input_size, 2 ) ##rnn_units

<b style= "color:cyan; font-size:20px">
 Writing a clean training loop from memory
</b>